const ACTIVITY_ACTIONS = {
  USER_REGISTERED: "USER_REGISTERED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PROFILE_PHOTO_ADDED: "PROFILE_PHOTO_ADDED",
  INTEREST_ADDED: "INTEREST_ADDED",
  FRIEND_REQUEST_SENT: "FRIEND_REQUEST_SENT",
  FRIEND_REQUEST_ACCEPTED: "FRIEND_REQUEST_ACCEPTED",
  USER_BLOCKED: "USER_BLOCKED",
  MATCH_CREATED: "MATCH_CREATED",
  SUBSCRIPTION_PURCHASED: "SUBSCRIPTION_PURCHASED",
};

module.exports = { ACTIVITY_ACTIONS };
